# Generated by Django 3.1.2 on 2020-10-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_transacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
