# Generated by Django 3.1.4 on 2021-01-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0008_evolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucao',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
