# Generated by Django 3.1.4 on 2021-01-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0009_evolucao_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucao',
            name='title',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
